# Generated by Django 3.1.7 on 2021-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210325_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
