# Generated by Django 3.1.7 on 2021-03-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210325_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
