# Generated by Django 3.1.7 on 2021-03-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviecomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('PLAY_NOW', 'Play Now'), ('WATCH_ONLINE', 'Watch Online'), ('UPCOMING', 'Upcoming')], default='PLAY_NOW', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(null=True),
        ),
    ]
