# Generated by Django 3.1.7 on 2021-03-31 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210331_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='movie_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='movie_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
