# Generated by Django 3.1.7 on 2021-03-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210331_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='content',
            field=models.TextField(),
        ),
    ]
