# Generated by Django 3.1.7 on 2021-03-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210331_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='user',
            new_name='creator',
        ),
    ]
