# Generated by Django 3.1.7 on 2021-03-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210320_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestorage',
            name='visibility',
        ),
    ]
